modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/IAFEnvoy/Jupiter/issues"
license = "GNU LGPL 3.0"

[[mods]]
modId = "jupiter"
version = "${version}"
displayName = "Jupiter"
authors = "IAFEnvoy"
description = '''
A powerful, auto sync config library.
'''
logoFile = "logo.png"

[[dependencies.jupiter]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jupiter]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"
